In [58]:
from warnings import filterwarnings
filterwarnings('ignore')

In [59]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

%matplotlib inline

In [60]:
df = pd.read_csv('./laptop_data.csv')

In [61]:
df.shape

(1303, 12)

In [62]:
df.columns

Index(['Unnamed: 0', 'Company', 'TypeName', 'Inches', 'ScreenResolution',
       'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight', 'Price'],
      dtype='object')

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1303 non-null   int64
 1   Company           1303 non-null   object
 2   TypeName          1303 non-null   object
 3   Inches            1303 non-null   float64
 4   ScreenResolution  1303 non-null   object
 5   Cpu               1303 non-null   object
 6   Ram               1303 non-null   object
 7   Memory            1303 non-null   object
 8   Gpu               1303 non-null   object
 9   OpSys             1303 non-null   object
 10  Weight            1303 non-null   object
 11  Price             1303 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 122.3+ KB

In [64]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [65]:
df = df.drop('Unnamed: 0',axis=1)

In [66]:
df['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: count, dtype: int64

In [67]:
df['TypeName'].value_counts()

TypeName
Notebook              727
Gaming                205
Ultrabook             196
2 in 1 Convertible    121
Workstation            29
Netbook                25
Name: count, dtype: int64

# Treating the Ram Column

In [68]:
df['Ram'] = df['Ram'].str.split('G').str[0]

In [69]:
df['Ram'] = df['Ram'].astype(int)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1303 non-null   object
 1   TypeName          1303 non-null   object
 2   Inches            1303 non-null   float64
 3   ScreenResolution  1303 non-null   object
 4   Cpu               1303 non-null   object
 5   Ram               1303 non-null   int32
 6   Memory            1303 non-null   object
 7   Gpu               1303 non-null   object
 8   OpSys             1303 non-null   object
 9   Weight            1303 non-null   object
 10  Price             1303 non-null   float64
dtypes: float64(2), int32(1), object(8)
memory usage: 107.0+ KB

In [73]:
df.drop('Memory',axis=1,inplace=True)

In [74]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

# Treating the Weight  Column

In [75]:
df['Weight'] = df['Weight'].str.split("k").str[0]

In [76]:
df['Weight'] = df['Weight'].astype(float)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1303 non-null   object
 1   TypeName          1303 non-null   object
 2   Inches            1303 non-null   float64
 3   ScreenResolution  1303 non-null   object
 4   Cpu               1303 non-null   object
 5   Ram               1303 non-null   int32
 6   Gpu               1303 non-null   object
 7   OpSys             1303 non-null   object
 8   Weight            1303 non-null   float64
 9   Price             1303 non-null   float64
dtypes: float64(3), int32(1), object(6)
memory usage: 96.8+ KB

## treating the GPU Column

In [78]:
df['Gpu'].value_counts()

Gpu
Intel HD Graphics 620      281
Intel HD Graphics 520      185
Intel UHD Graphics 620      68
Nvidia GeForce GTX 1050     66
Nvidia GeForce GTX 1060     48
                          ...
AMD Radeon R5 520            1
AMD Radeon R7                1
Intel HD Graphics 540        1
AMD Radeon 540               1
ARM Mali T860 MP4            1
Name: count, Length: 110, dtype: int64

In [79]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080

In [80]:
df['TypeName'].value_counts()

TypeName
Notebook              727
Gaming                205
Ultrabook             196
2 in 1 Convertible    121
Workstation            29
Netbook                25
Name: count, dtype: int64

In [107]:
df['OpSys'].value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         27
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

In [81]:
from sklearn.preprocessing import OrdinalEncoder

ordencode = OrdinalEncoder(categories=[['Notebook','Gaming','Ultrabook','2 in 1 Convertible','Workstation','Netbook']])

In [82]:
encoded = ordencode.fit_transform(df[['TypeName']])

In [83]:
encoded = pd.DataFrame(encoded,columns=ordencode.get_feature_names_out())

In [84]:
df.drop('TypeName',axis=1,inplace=True)

In [85]:
final_df = pd.concat([df,encoded],axis=1)

In [86]:
final_df.head()

,Company,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price,TypeName
0,Apple,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,2.0
1,Apple,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,47895.5232,2.0
2,HP,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86,30636.0000,0.0
3,Apple,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83,135195.3360,2.0
4,Apple,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080,2.0

# *Seperating the independent and Dependent Volume*

In [87]:
X = df.drop('Price',axis=1)
y = df['Price']

In [88]:
X.head()

,Company,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight
0,Apple,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37
1,Apple,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34
2,HP,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86
3,Apple,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83
4,Apple,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37

In [89]:
y.head()

0     71378.6832
1     47895.5232
2     30636.0000
3    135195.3360
4     96095.8080
Name: Price, dtype: float64

In [90]:
df.head()

,Company,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price
0,Apple,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832
1,Apple,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,47895.5232
2,HP,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86,30636.0000
3,Apple,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83,135195.3360
4,Apple,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080

# *Scaling The Xtrain And Xtest*

In [38]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

In [91]:
Xencoded = ohe.fit_transform(X[['Company', 'ScreenResolution', 'Cpu', 'Gpu', 'OpSys']]).toarray()

In [92]:
X = pd.DataFrame(Xencoded,columns=ohe.get_feature_names_out())

In [106]:
X.head()

,Company_Acer,Company_Apple,Company_Asus,Company_Chuwi,Company_Dell,Company_Fujitsu,Company_Google,Company_HP,Company_Huawei,Company_LG,...,Gpu_Nvidia Quadro M620M,OpSys_Android,OpSys_Chrome OS,OpSys_Linux,OpSys_Mac OS X,OpSys_No OS,OpSys_Windows 10,OpSys_Windows 10 S,OpSys_Windows 7,OpSys_macOS
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

# *Perfoming Train Test Split*

In [94]:
from sklearn.model_selection import train_test_split

Xtrain, Xtest, ytrain, ytest= train_test_split(X,y, test_size=0.20, random_state=42)

In [95]:
Xtrain.shape, Xtest.shape

((1042, 296), (261, 296))

In [96]:
ytrain.shape, ytest.shape

((1042,), (261,))

# *Scaling the Xtrain And Xtest*

In [97]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [98]:
data = scaler.fit_transform(Xtrain)

scaled_Xtrain = pd.DataFrame(data,columns=scaler.get_feature_names_out())

In [99]:
scaled_Xtrain

,Company_Acer,Company_Apple,Company_Asus,Company_Chuwi,Company_Dell,Company_Fujitsu,Company_Google,Company_HP,Company_Huawei,Company_LG,...,Gpu_Nvidia Quadro M620M,OpSys_Android,OpSys_Chrome OS,OpSys_Linux,OpSys_Mac OS X,OpSys_No OS,OpSys_Windows 10,OpSys_Windows 10 S,OpSys_Windows 7,OpSys_macOS
0,-0.292261,-0.136282,-0.377550,-0.053734,-0.530729,-0.030994,-0.053734,1.961253,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,4.408103,-2.104064,-0.076102,-0.1998,-0.103292
1,-0.292261,-0.136282,2.648657,-0.053734,-0.530729,-0.030994,-0.053734,-0.509878,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292
2,-0.292261,-0.136282,-0.377550,-0.053734,-0.530729,-0.030994,-0.053734,1.961253,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292
3,-0.292261,-0.136282,-0.377550,-0.053734,1.884202,-0.030994,-0.053734,-0.509878,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292
4,-0.292261,-0.136282,-0.377550,-0.053734,-0.530729,-0.030994,-0.053734,-0.509878,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1037,3.421596,-0.136282,-0.377550,-0.053734,-0.530729,-0.030994,-0.053734,-0.509878,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292
1038,-0.292261,-0.136282,-0.377550,-0.053734,-0.530729,-0.030994,-0.053734,1.961253,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292
1039,-0.292261,-0.136282,-0.377550,-0.053734,-0.530729,-0.030994,-0.053734,1.961253,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292
1040,-0.292261,-0.136282,-0.377550,-0.053734,-0.530729,-0.030994,-0.053734,-0.509878,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292
1041,-0.292261,-0.136282,-0.377550,-0.053734,-0.530729,-0.030994,-0.053734,-0.509878,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292

In [100]:
data = scaler.transform(Xtest)

scaled_Xtest = pd.DataFrame(data,columns=scaler.get_feature_names_out())

In [101]:
scaled_Xtest.head()

,Company_Acer,Company_Apple,Company_Asus,Company_Chuwi,Company_Dell,Company_Fujitsu,Company_Google,Company_HP,Company_Huawei,Company_LG,...,Gpu_Nvidia Quadro M620M,OpSys_Android,OpSys_Chrome OS,OpSys_Linux,OpSys_Mac OS X,OpSys_No OS,OpSys_Windows 10,OpSys_Windows 10 S,OpSys_Windows 7,OpSys_macOS
0,-0.292261,-0.136282,-0.37755,-0.053734,-0.530729,-0.030994,-0.053734,-0.509878,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292
1,-0.292261,-0.136282,-0.37755,-0.053734,-0.530729,-0.030994,-0.053734,1.961253,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292
2,-0.292261,-0.136282,-0.37755,-0.053734,-0.530729,-0.030994,-0.053734,-0.509878,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292
3,-0.292261,-0.136282,-0.37755,-0.053734,-0.530729,-0.030994,-0.053734,-0.509878,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292
4,-0.292261,-0.136282,-0.37755,-0.053734,-0.530729,-0.030994,-0.053734,1.961253,-0.030994,-0.053734,...,-0.030994,-0.043853,-0.150237,-0.226855,-0.08796,-0.226855,0.475271,-0.076102,-0.1998,-0.103292

# *Traning The Model*

In [102]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [103]:
model.fit(scaled_Xtrain,ytrain)

LinearRegression()

In [104]:
ypred = model.predict(scaled_Xtest)

In [105]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

print(f"Mean Squared Error: {mean_squared_error(ypred,ytest)}")
print(f"Mean Absolute Error: {mean_absolute_error(ypred,ytest)}")
print(f"R2 Score: {r2_score(ypred,ytest)}")

Mean Squared Error: 8.243591106477142e+35
Mean Absolute Error: 1.7232222628429405e+17
R2 Score: -0.020757812996194946